# Unique project key in SonarQube (already created manually)
sonar.projectKey=node-ci-cd-demo
sonar.projectName=node-ci-cd-demo

# Source code folder
sonar.sources=.

# Exclude heavy or irrelevant folders
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**

# Test folder (optional, if you have tests in a separate folder)
# sonar.tests=tests

# Coverage report path (from Jest or other JS test tool)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarQube server URL and authentication token
sonar.host.url=http://107.20.60.100:9000
sonar.login=squ_0b151f11a4287e305d50a74241e49e3898e20957

# Optional: set language explicitly (SonarQube usually detects JS automatically)
# sonar.language=js
