# Unique key for your project in 
sonar.projectKey=node-ci-cd-demo
sonar.projectName=node-ci-cd-demo
sonar.sources=.
sonar.host.url=http://107.20.60.100:9000 
sonar.login=squ_0b151f11a4287e305d50a74241e49e3898e20957

# Optional: you can specify tests folder
# sonar.tests=tests

# Optional: language (if needed)
# sonar.language=js
